# This is a basic workflow to help you get started with Actions

name: Deploy

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  predeploy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.values }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - id: matrix
        run: echo "values=[$(ls ./apps/ | grep -v -e '^shared$' -e '^core$' | sed 's/.*/"&"/' | paste -sd, -)]" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.matrix.outputs.values }}"
      - run: pnpm install
      - run: pnpm --filter @greysmm.github.io/shared run build
      - run: pnpm --filter @greysmm.github.io/core run build
      - run: |
          git config --global user.email "deployment"
          git config --global user.name "deployment"
          git remote set-url origin https://greysmm:${{ secrets.TOKEN }}@github.com/greysmm/greysmm.github.io.git
          cp ./apps/core/dist/index.html ./apps/core/dist/404.html
          pnpm gh-pages -d ./apps/core/dist -b deploy-core
  build:
    needs: [ predeploy ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJSON(needs.predeploy.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - run: pnpm install
      - run: pnpm --filter @greysmm.github.io/shared run build
      - run: pnpm --filter @greysmm.github.io/${{ matrix.value }} run build
      - run: |
          git config --global user.email "deployment"
          git config --global user.name "deployment"
          git remote set-url origin https://greysmm:${{ secrets.TOKEN }}@github.com/greysmm/greysmm.github.io.git
          pnpm gh-pages -d ./apps/${{ matrix.value }}/dist -b deploy-${{ matrix.value }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/${{ matrix.value }}/dist'
          name: deploy-${{ matrix.value }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
