# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  predeploy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.workspaces }}
    steps:
      - id: matrix
        run: echo "workspaces=[$(ls apps/ | grep -v -e '^shared$' -e '^core$' | sed 's/.*/"&"/' | paste -sd, -)]" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - run: pnpm install
      - run: pnpm --filter @greysmm.github.io/shared run build
      - run: pnpm --filter @greysmm.github.io/core run build
      - run: |
          git config --global user.email "deployment"
          git config --global user.name "deployment"
          git remote set-url origin https://greysmm:${{ secrets.TOKEN }}@github.com/greysmm/greysmm.github.io.git
          cp ./apps/core/dist/index.html ./apps/core/dist/404.html
          pnpm gh-pages -d ./apps/core/dist -b core
  build:
    needs: [ predeploy ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJSON(needs.predeploy.outputs.matrix) }}
    steps:
      - run: echo "${{ matrix.value }}"
