# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm predeploy
      # - run: pnpm run deploy
      - name: Deploy
        env:
          MY_EMAIL: g
          MY_NAME: g
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/greysmm/greysmm.github.io.git
          pnpm run deploy
